In [ ]:
import numpy as np
filename = "Data_P1/msr_test_symmetric.txt"

# Read data from the file
with open(filename, 'r') as f:
    # Read the first line as a string
    SorN = [next(f)]
    lines = f.readlines()
SorN= SorN[0].strip().split()
header = lines[0].strip().split()
n = int(header[0])
fillings = []
data = [line.strip().split() for line in lines[1:]]
ids = np.array([int(item[0]) for item in data])
ids_rows = ids[0:n+1]  # Extracting row indices
ids_cols = ids[n+1:len(ids)]  # Extract column indices
ids_cols = ids_cols-1  # Adjust column indices to be zero-based
print("Column indices:", ids_cols)

for i in range(len(ids_rows) - 1): # only consider the row elements
    fillings.append(ids_rows[i+1] - ids_rows[i])  # append filling numbers

print("amoun of nonzero values per row:", fillings)

vals = np.array([float(item[1]) for item in data])  # Convert to floats and extract values of matrix

diag = np.diag(vals[0:n]) # Read diagonal elements
vals = vals[n+1:len(vals)]  # Exclude diagonal elements from vals
print(f"values: {vals}")

matrix = np.zeros((n, n)) # Initialize the matrix




dict_fillings = {}  # Initialize dict_fillings as an empty dictionary
for i in range(len(fillings)):
    dict_fillings[i] = fillings[i]

# Use dictionaries to fill the matrix
for i in range(n):
    if dict_fillings[i] == 0:
        continue  # Skip rows with no fillings
    start_idx = sum(fillings[:i])  # Calculate the starting index for the current row
    end_idx = start_idx + fillings[i]  # Calculate the ending index for the current row
    for idx, j in enumerate(ids_cols[start_idx:end_idx]):
        if idx < len(vals):  # Ensure we don't exceed the length of vals
            matrix[i, j] = vals[start_idx + idx]
matrix = matrix + diag
if SorN[0] == "s":
    matrix = matrix + matrix.T  # Make the matrix symmetric
print("Matrix:\n", matrix)




Column indices: [0 1 2]
amoun of nonzero values per row: [0, 0, 1, 2]
values: [ 2.  4. -1.]
['s']
Matrix:
 [[ 8.  0.  2.  0.]
 [ 0. 16.  0.  4.]
 [ 2.  0. 10. -1.]
 [ 0.  4. -1. 16.]]


Correct answer should be 

4 0 0 0 

0 8 0 0

2 0 5 0

0 4 -1 8 


In [ ]:
print("Matrix shape:", matrix.shape)
# Fill values based on the fillings and column indices
for val, col, group_id in zip(vals, ids_cols, range(1, len(vals) + 10)):
    #print(f"Values of filling:{fillings[i]} at row {row_idx}, group {group}")
    for row_idx, group in enumerate(fillings):
        if group == group_id:
            matrix[row_idx, col] = val
            placed = True
            #print(f"Placing value {val} at row {row_idx}, column {col}")


print(matrix+diag)
